version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "02:32"
  open-pull-requests-limit: 1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "14:11"
  open-pull-requests-limit: 1
