name: File Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - ros-tooling/action-ros-lint
          - ros-tooling/keyboard_handler
        include:
          - repo: ros-tooling/action-ros-lint
            default_branch: master
          - repo: ros-tooling/keyboard_handler
            default_branch: main
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v2
      - name: File Sync
        uses: emersonknapp/github-action-file-sync@master
        with:
          # NOTE: you must provide the PR origin branch name here, otherwise it will try to push to the default branch
          REPOSITORIES: ${{ matrix.repo }}@repo-config-sync
          FILES: |
            .github/workflows/autoapprove.yml=.github/workflows/autoapprove.yml
            .github/workflows/automerge.yml=.github/workflows/automerge.yml
            sync/.github/dependabot.yml=.github/dependabot.yml
            sync/.github/CODEOWNERS=.github/CODEOWNERS
          PULL_REQUEST_BRANCH_NAME: ${{ matrix.default_branch }}
          PULL_REQUEST_LABEL: file-sync
          TOKEN: ${{ secrets.REPO_CONFIG_SYNC_TOKEN }}
