name: File Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v2
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@v2.0.0
        with:
          REPOSITORIES: |
            ros-tooling/action-ros-lint
          FILES: |
            sync/.github/dependabot.yml=.github/dependabot.yml
            sync/.github/CODEOWNERS=.github/CODEOWNERS
          PULL_REQUEST_BRANCH_NAME: repo-config-sync
          TOKEN: ${{ secrets.REPO_CONFIG_SYNC_TOKEN }}
