name: File Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v2
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@2.0.10
        with:
          REPOSITORIES: |
            ros-tooling/test-repo-target@repo-config-sync
          FILES: |
            .github/workflows/autoapprove.yml=.github/workflows/autoapprove.yml
            .github/workflows/automerge.yml=.github/workflows/automerge.yml
            sync/.github/dependabot.yml=.github/dependabot.yml
            sync/.github/CODEOWNERS=.github/CODEOWNERS
          PULL_REQUEST_BRANCH_NAME: main
          TOKEN: ${{ secrets.REPO_CONFIG_SYNC_TOKEN }}
