name: File Sync

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@v2
      - name: File Sync
        uses: emersonknapp/github-action-file-sync@master
        with:
          REPOSITORIES: |
            ros-tooling/action-ros-lint@repo-config-sync
          FILES: |
            .github/workflows/autoapprove.yml=.github/workflows/autoapprove.yml
            .github/workflows/automerge.yml=.github/workflows/automerge.yml
            sync/.github/dependabot.yml=.github/dependabot.yml
            sync/.github/CODEOWNERS=.github/CODEOWNERS
          PULL_REQUEST_BRANCH_NAME: master
          PULL_REQUEST_LABEL: file-sync
          TOKEN: ${{ secrets.REPO_CONFIG_SYNC_TOKEN }}
